apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:/hrgIMuHjNNI3hyyUN9hkQsC0PqvIfqungJSnVtqOdNj5SWN,iv:bsVeP6PrpkJR/mMWJCmfpjiu8jhS+TQqLHyLZmyWWdE=,tag:W9ru7mafQIfbIys81UxvmQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:G9BlPe0mKb900htcq8kzM2aXCKdpJ1LyyhnsG3HVZBznncNnNvf9F2c3fxSDAOSXXyl5sJ3ht5sqqgAx3zy8EQhlbwN+rWWJAAZ8rw76+3bP3j6Q/wEzDNXd6JASc9kQspejhIpMUIdT5HzHt4OKfOZnBOGoY5+OEaraAVerTBEOZOqqDfIuNsLSw0jYQhXU2v/xDvNL1MzQrYP0ON5p1z8jUCoycSOUDUJBk+dibw==,iv:V2gjL7x620LuytfPeYxgMAdXKfYetyCR56gYlKCgBYM=,tag:xWeKiySwcZ0iouSTTv7AHg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pzw4yze9v74zrhw3drflmhzqq4fkrkjlf8entyy9wc9jrvrtuv8q73sln9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2MnlQRUJjUmVnOXhoc1RV
            cWtTSHZ1OFFCaEJJWnJwRVNybmM2UUJISlM0CldGa2ptYklNdkVIRVMzbEYramFI
            VjZuaXg4eUx0RVR2OFZJNS9nSzRwOWcKLS0tIHJYN1FTRWYrejdRTFJ6SnorOGww
            RWNwWkZXYVlBY2N0RXBhc01YZFQ0djAKRcEtuk11MOw20FLJtlbkkOXXB1+5RLo0
            g3750NvgqEOqy0O11PoyLSPHT+WtVoywjlPwwKsqqUGwua4sdX2dtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-07T05:24:23Z"
    mac: ENC[AES256_GCM,data:UjErNQkRIt9bNrVMZW8v4nEVn9I2iFBmKM7UJ2cvmtm/zeKodwLMaWlKA98sgl8lIa/Vck9Ho9EFT9URwcKb//e9B/oNzAjRYehJGd4ShK3pMI/a+3+0y+LBpLqOg+qkSoCnyZd1W6eZGQJKoNtcaegfDqtxH6SlkZZ3ojE64Uo=,iv:PJ1DWBd8F77RXrCcy53FzFbpW+FYyaEIKqb31Cc/lFU=,tag:b1Qt9W0ebK9qvG9ZS//eMQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
